vector_object_server:
  ros__parameters:
    use_sim_time: true
    map_topic: "/keepout_filter_mask"
    global_frame_id: "map"
    enforce_global_frame_id: false
    transform_tolerance: 0.1
    resolution: 0.05
    width: 40.0
    height: 40.0
    origin_x: -20.0
    origin_y: -20.0
    default_value: 0
    trigger_costmap_clear_on_shape_update: true
    update_frequency: 1.0
    shapes: ["Poly", "Circle"]
    Poly:
      type: "polygon"
      frame_id: "map"
      closed: true
      value: 100
      points: [2.0, -1.0, 4.0, -1.0, 4.0, 1.0, 2.0, 1.0]
    Circle:
      type: "circle"
      frame_id: "map"
      fill: true
      value: 100
      center: [8.0, 2.0]
      radius: 1.2

keepout_costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "/keepout_costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0
