<?xml version="1.0"?>
<package format="3">
  <name>nav2_colregs_costmap_layers</name>
  <version>1.0.0</version>
  <description>Custom Nav2 costmap layer plugins for COLREGS (TS projection).</description>
  <maintainer email="vectorwang@hotmail.com">Vector Wang</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>nav2_costmap_2d</depend>
  <depend>nav2_colregs_msgs</depend>
  <depend>rclcpp</depend>
  <depend>pluginlib</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <costmap_2d plugin="${prefix}/plugins.xml" />
  </export>
</package>
